const ProductItens = [
  {
    id: 1,
    referencia: 38416710,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V8 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4,
    price: 250,
    priceDiscount: 149.9,
  },
  {
    id: 2,
    referencia: 38416711,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V8 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 3.2,
    price: 400,
  },
  {
    id: 3,
    referencia: 38416712,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.5,
    price: 300,
    priceDiscount: 249.9,
  },
  {
    id: 4,
    referencia: 38416713,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.9,
    price: 300,
  },
  {
    id: 5,
    referencia: 38416714,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.6,
    price: 200,
    priceDiscount: 149.9,
  },
  {
    id: 6,
    referencia: 38416715,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.7,
    price: 200,
    priceDiscount: 149.9,
  },
  {
    id: 7,
    referencia: 38416716,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.2,
    price: 600,
  },
  {id: 8,
    referencia: 38416717,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.6,
    price: 200,
    priceDiscount: 149.9,
  },
  {
    id: 9,
    referencia: 38416718,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.9,
    price: 400,
  },
  {
    id: 10,
    referencia: 38416719,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.3,
    price: 350,
    priceDiscount: 199.9,
  },
  {
    id: 11,
    referencia: 38416720,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 2.3,
    price: 650,
  },
  {
    id: 12,
    referencia: 38416721,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 3.5,
    price: 480,
    priceDiscount: 349.9,
  },
  {
    id: 13,
    referencia: 38416722,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 3.8,
    price: 250,
  },
  {
    id: 14,
    referencia: 38416718,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 3.2,
    price: 280,
    priceDiscount: 149.9,
  },
  {
    id: 15,
    referencia: 38416718,
    image: 'public/produc-image-5.jpeg',
    name: 'K-Swiss V9 - Masculino',
    tipo:'Tênis',
    tamanho: ['38', '39', '40', '41','42'],
    cor:['var(--color-primary)', 'var(--color-primary-2)', 'var(--color-error)', 'var(--color-success'],
    avaliacao: 4.9,
    price: 400,
  },
]
export default ProductItens;
